### ISSUE TITLE
How to remove a previously used choices class?

### ISSUE THREAD

**Issue by Mapiarz** [bellini666/django-choices-field#11]
In one of my old migrations I have:
```python
        migrations.AlterField(
            model_name='maintenancetask',
            name='state',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Open'), (32767, 'Closed')], choices_enum=models.maintenance.MaintenanceTaskState, default=1),
        ),
```

Today, I want to remove the `state` field and the `MaintenanceTaskState` class along with it. But I can't, since it's referenced in the old migration.

Any tips on how to proceed @bellini666 ? :)

**Comment by bellini666** [comment]
Hi @Mapiarz ,

I've had that issue as well =P. This is something that I want to improve in the future.

What I usually do is to go to those old migrations and create a copy of the old class in that file, and reference it in the `choices_enum` argument.

Tell me if that works out for you

**Comment by Mapiarz** [comment]
That works for me, thanks @bellini666!
